### PR TITLE
Use a bbox filter field facet class to obviate Blacklight overrides

### LINKED ISSUE #996: Some helper methods are not overrideable when using zeitwerk loader in Rails 6.0, 6.1
### Descriptive summary

When using the zeitwerk loader in Rails 6.0,6.1 some helper methods, `Geoblacklight::ViewHelperOverride` are not overrideable.

### Expected behavior
These should be able to be extended for custom functionality.

Likely do to how we initialize things here: https://github.com/geoblacklight/geoblacklight/blob/main/lib/geoblacklight.rb#L38-L46

Not present in the classic loader and users who never override these methods will not see these problems.

### LINKED ISSUE #1146: DEPRECATION WARNING: constraint_query_label is deprecated and will be removed from a future release (Moving to Blacklight::ConstraintsComponent)
### Descriptive summary

Warning can be triggered via a search result set. Use [Blacklight::ConstraintsComponent](https://github.com/projectblacklight/blacklight/blob/fd33c74a378d164a571174fa0054c25b70ef09d1/app/components/blacklight/constraints_component.rb) instead.

### Expected behavior

No deprecation warnings

### Actual behavior

Seeing deprecation warnings.

### Steps to reproduce the behavior

1. Spin up GBL
1. View a search results page ([Example](http://localhost:3000/?search_field=all_fields&q=))

### Related work

https://github.com/geoblacklight/geoblacklight/issues/1133

### PR DESCRIPTION
**Pull request by ewlarson**
This PR replaces a mix of Blacklight helper overrides (which bubble a BL deprecation warning, see #1146) and search builder customizations, in favor of a new `Geoblacklight::BboxFilterField` (responsible for mapping user parameters to Geoblacklight::BoundingBoxes) and `Geoblacklight::BboxFilterQuery` (responsible for mapping the FilterField to solr parameters).

This PR will also close (#996) an issue where the Blacklight overrides were no longer locally overridable.

Defines this new facet in the catalog_controller.rb template file:

```
    # GEOBLACKLIGHT APPLICATION FACETS

    # Map-Based "Search Here" Feature
    # item_presenter       - Defines how the facet appears in the GBL UI
    # filter_query_builder - Defines the query generated for Solr
    # filter_class         - Defines how to add/remove facet from query
    # label                - Defines the label used in contstraints container
    config.add_facet_field Settings.FIELDS.SPATIAL_EXTENT, item_presenter: Geoblacklight::BboxItemPresenter, filter_class: Geoblacklight::BboxFilterField, filter_query_builder: Geoblacklight::BboxFilterQuery, within_boost: Settings.BBOX_WITHIN_BOOST, overlap_boost: Settings.OVERLAP_RATIO_BOOST, overlap_field: Settings.FIELDS.OVERLAP_FIELD, label: 'Bounding Box'

```

Fixes #1146
Fixes #996 

Upstream Blacklight TODOs:
- [ ] https://github.com/projectblacklight/blacklight/pull/2626 (allows us to remove the ViewHelperOverride entirely)
- [ ] https://github.com/projectblacklight/blacklight/pull/2623 (allows us to remove the custom FacetItemPresenter)
---
* Remove: view_helper_override.rb
* Remove: catalog_helper_override.rb
* Remove: spatial_search_behavior.rb
* Add: suppressed_records_search_behavior.rb
* Add: facet config to catalog_controller.rb template
* Add: bbox_filter_field.rb
* Add: bbox_filter_query.rb
* Add: bbox_item_presenter.rb
* Add: bbox_filter_field_spec
* Add: bbox_filter_query_spec
* Add: bbox_item_presenter_spec

### CODE REVIEW

File: app/models/concerns/geoblacklight/bbox_filter_field.rb [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+      new_state.reset(params)
+    end
+
+    # @param [String,#value] a filter to remove from the url
+    # @return [Blacklight::SearchState] new state
+    def remove(_item)
+      new_state = search_state.reset_search
+      params = new_state.params
+      # value = as_url_parameter(item)
```
Comment (eliotjordan) [inline app/models/concerns/geoblacklight/bbox_filter_field.rb:22]: issue: remove commented line.

File: lib/generators/geoblacklight/templates/catalog_controller.rb [hunk 2]
```diff
@@ -111,6 +111,15 @@ class CatalogController < ApplicationController
...
     config.add_facet_field Settings.FIELDS.SOURCE, :label => 'Collection', :limit => 8, :show => false
 
+    # GEOBLACKLIGHT APPLICATION FACETS
+
+    # Map-Based "Search Here" Feature
+    # item_presenter       - Defines how the facet appears in the GBL UI
+    # filter_query_builder - Defines the query generated for Solr
+    # filter_class         - Defines how to add/remove facet from query
+    # label                - Defines the label used in contstraints container
+    config.add_facet_field Settings.FIELDS.SPATIAL_EXTENT, item_presenter: Geoblacklight::BboxItemPresenter, filter_class: Geoblacklight::BboxFilterField, filter_query_builder: Geoblacklight::BboxFilterQuery, within_boost: Settings.BBOX_WITHIN_BOOST, overlap_boost: Settings.OVERLAP_RATIO_BOOST, overlap_field: Settings.FIELDS.OVERLAP_FIELD, label: 'Bounding Box'
```
Comment (eliotjordan) [inline lib/generators/geoblacklight/templates/catalog_controller.rb:121]: question: This is a gnarly facet field configuration! Why were `within_boost`, `overlap_boost`, and `overlap_field` added as field configs rather than just referenced in the code? Testing?

**Review by eliotjordan — CHANGES_REQUESTED** [review]

File: lib/generators/geoblacklight/templates/catalog_controller.rb (hunk 2 above)
Comment (ewlarson) [reply lib/generators/geoblacklight/templates/catalog_controller.rb:121]: Sure. Chris added those additional args in his last revision. I imagine he felt articulating all these options in the facet field configuration was the most transparent place to capture these settings. I'm fine with it, even though it feels oversized compared to all the other facet definitions.

**Review by eliotjordan — APPROVED** [review]
