### PR TITLE
Force capybara to wait for relationships to fade in before running aXe

### LINKED ISSUE #1506: Relations widget fails accessibility tests in CI
### Descriptive summary

The aXe a11y tests that run in CI are reporting color contrast errors stemming from the relations widget:

```
1) color-contrast: Elements must meet minimum color contrast ratio thresholds (serious)
           https://dequeuniversity.com/rules/axe/4.9/color-contrast?application=axeAPI
           The following 12 nodes violate this rule:
           
               Selector: .relationship-member_of_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Belongs to collection...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-member_of_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record">
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-part_of_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Is part of...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-part_of_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record">
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-relation_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Related records...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-relation_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record"><span class="icon-missing geoblacklight-none"></span>The Related Record</a>
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-replaces_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Replaces...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-replaces_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record"><span class="icon-missing geoblacklight-none"></span>The Related Record</a>
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-source_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Source records...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-source_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record">
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-version_of_ancestors > .card-header > h2
               HTML: <h2 class="mb-0 h6">Is version of...</h2>
               Fix any of the following:
               - Element has insufficient color contrast of 1.16 (foreground color: #eceded, background color: #fefefe, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
               
               Selector: .relationship-version_of_ancestors > .list-group.list-group-flush > .border-bottom-0.list-group-item > a[href$="the-related-record"]
               HTML: <a href="/catalog/the-related-record">
               Fix any of the following:
               - Element has insufficient color contrast of 1.11 (foreground color: #ebf3ff, background color: #ffffff, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
```

See e.g. https://github.com/geoblacklight/geoblacklight/actions/runs/10375337056/job/28725735086?pr=1503.

### PR DESCRIPTION
**Pull request by thatbudakguy**
Fixes #1506.

The relationships panel is inserted into the page and then faded in using an animation with a 200ms timing, so it's possible that aXe is seeing it halfway faded-in and calculating color contrast ratios off of that, since the colors are not what we actually see when loading it in the browser.

### CODE REVIEW

File: spec/features/axe_spec.rb [hunk 1]
```diff
@@ -17,6 +17,7 @@
 
     it "validates an item page with relationships" do
       visit solr_document_path("all-relationships")
+      sleep 0.5 # wait for relationships to be fully visible / faded in
```
Comment (jcoyne) [inline spec/features/axe_spec.rb:20]: Instead of a sleep you can expect(page).to have_content "thing that faded in".
